# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9966759234752ac03801f6cebbb1a56a7a09acffafd0361263fb3801dc3aa1f8a2393697ed4e88449d096dd55f4ed579c81fec591a7aa7efbcbdd2cce5e50bd

test:
  secret_key_base: 409313de0d1d7a64a1fccc2330df82092751bdb1afe625de5d09c0cf9736fd39c8aa626a609473db86eefa1c40e30737ed6bdd567a866fbfe692a18013ffab58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
